// Offline candidates: same BF16 input and amax*float32(1/448) scale policy.
// After clearing sign, all finite BF16 encodings fit positive signed i16 and
// their integer ordering is exactly the ordering of their absolute values.
#ifndef USE_LUT
#define USE_LUT 0
#endif
#ifndef CORRECT_QUOTIENT
#define CORRECT_QUOTIENT 1
#endif
#ifndef AMAX_CHAINS
#define AMAX_CHAINS 1
#endif
#if USE_LUT
#define ALL_GROUPS (SW_WR_LOWER_GROUP0|SW_WR_UPPER_GROUP0|SW_WR_LOWER_GROUP1|SW_WR_UPPER_GROUP1|SW_WR_LOWER_GROUP2|SW_WR_UPPER_GROUP2|SW_WR_LOWER_GROUP3|SW_WR_UPPER_GROUP3)
static inline float64 lookup_reciprocal(float64 maximum,float64 low,float64 high,float64 floor_reciprocal) {
 uint64 word=(uint64)maximum;
 uint64 mantissa=(word>>16)&127;
 // SHUFFLE is byte-addressed within each 64-byte dual group. Select one
 // FP32 entry in each group, then broadcast the selected one of four groups.
 uint64 control=0x83828180u+(mantissa&15)*0x04040404u;
 // The control addresses BYTES: use byte SHUFFLE explicitly. F32 SHUFFLE
 // interprets source-element by element size and does not implement this map.
 float64 lo=(float64)v_u8_shuffle_b((uchar256)low,(uchar256)control,0,0);
 float64 hi=(float64)v_u8_shuffle_b((uchar256)high,(uchar256)control,0,0);
 float64 selected=v_f32_sel_geq_u32_b(mantissa,64,hi,lo);
 uint64 group=(read_lane_id_4b_b()>>4)&3;
 selected=v_f32_sel_eq_u32_b((mantissa>>4)&3,group,selected,0);
 float64 swapped=v_f32_mov_dual_group_all_b(selected,-1,1,0,3,2,ALL_GROUPS,0);
 selected=v_f32_max_b(selected,swapped);
 swapped=v_f32_mov_dual_group_all_b(selected,-1,2,3,0,1,ALL_GROUPS,0);
 selected=v_f32_max_b(selected,swapped);
 int64 exponent=(int64)(word>>23)-127;
 selected=(float64)((uint64)selected-(uint64)(exponent*0x800000));
 return v_f32_sel_less_f32_b(maximum,1e-10f,floor_reciprocal,selected);
}
#undef ALL_GROUPS
#endif
static inline float64 native_value(float64 x,float64 scale,float64 reciprocal) {
 float64 z=x*reciprocal;
#if CORRECT_QUOTIENT
 float64 residual=v_f32_mac_b(-z,scale,x);
 z=v_f32_mac_b(residual,reciprocal,z);
#endif
 float64 magnitude=v_f32_min_b((float64)((uint64)z&0x7fffffff),448.f);
 // Preserve OCP-then-native double RNE in the small-value interval.
 float64 tiny=v_convert_i32_to_f32_b(v_convert_f32_to_i32_b(magnitude*512.f,SW_RHNE))*(1.f/1024.f);
 float64 value=v_f32_sel_less_f32_b(magnitude,0.03125f,tiny,magnitude*0.5f);
 return (float64)((uint64)value|((uint64)x&0x80000000));
}
#if USE_LUT
// reciprocal_table is FP32 [129]: entries0..127 normalize BF16 amax to[1,2),
// entry128 is for the exact floor-scale expression. Generated by CPU gate.
void main(tensor input,tensor reciprocal_table,tensor output,tensor scales) {
#else
void main(tensor input,tensor output,tensor scales) {
#endif
 int5 begin=get_index_space_offset(),end=begin+get_index_space_size();
 int width=get_dim_size(input,0);
#if USE_LUT
 int5 table_at={0,0,0,0,0};float64 table_low=v_f32_ld_tnsr_b(table_at,reciprocal_table);
 table_at[0]=64;float64 table_high=v_f32_ld_tnsr_b(table_at,reciprocal_table);
 table_at[0]=128;float64 floor_reciprocal=v_f32_ld_g(gen_addr(table_at,reciprocal_table));
#endif
 for(int row=begin[0];row<end[0];++row) {
  short128 maximum_bits=0;
#if AMAX_CHAINS == 4
  short128 maximum1=0,maximum2=0,maximum3=0;
  for(int k=0;k<width;k+=512) {
   int5 p0={k,row,0,0,0},p1={k+128,row,0,0,0};
   int5 p2={k+256,row,0,0,0},p3={k+384,row,0,0,0};
   short128 a=(short128)((ushort128)v_bf16_ld_tnsr_b(p0,input)&0x7fff);
   short128 b=(short128)((ushort128)v_bf16_ld_tnsr_b(p1,input)&0x7fff);
   short128 c=(short128)((ushort128)v_bf16_ld_tnsr_b(p2,input)&0x7fff);
   short128 d=(short128)((ushort128)v_bf16_ld_tnsr_b(p3,input)&0x7fff);
   maximum_bits=v_i16_max_b(maximum_bits,a);maximum1=v_i16_max_b(maximum1,b);
   maximum2=v_i16_max_b(maximum2,c);maximum3=v_i16_max_b(maximum3,d);
  }
  maximum_bits=v_i16_max_b(v_i16_max_b(maximum_bits,maximum1),v_i16_max_b(maximum2,maximum3));
#else
  for(int k=0;k<width;k+=128) {
   int5 p={k,row,0,0,0};
   short128 magnitude=(short128)((ushort128)v_bf16_ld_tnsr_b(p,input)&0x7fff);
   maximum_bits=v_i16_max_b(maximum_bits,magnitude);
  }
#endif
  maximum_bits=v_i16_reduce_max(maximum_bits);
  float64 maximum=v_convert_bf16_to_f32_b((bfloat128)maximum_bits,0);
  float64 scale=v_f32_max_b(maximum,1e-10f)*(1.f/448.f);
#if USE_LUT
  float64 reciprocal=lookup_reciprocal(maximum,table_low,table_high,floor_reciprocal);
#else
  float64 reciprocal=v_reciprocal_f32(scale);
#endif
  int5 scale_at={0,row,0,0,0};v_f32_st_tnsr_partial(scale_at,scales,scale*2.f,0,0);
  #pragma loop_unroll(4)
  for(int k=0;k<width;k+=128) {
   int5 p={k,row,0,0,0};
   float128 x=v_convert_bf16_to_f32_all_b(v_bf16_ld_tnsr_b(p,input));
   minifloat256 sparse=0;
   sparse=v_convert_f32_to_f8_b(native_value(x.v1,scale,reciprocal),0,SW_RHNE|SW_CLIP_FP,sparse);
   sparse=v_convert_f32_to_f8_b(native_value(x.v2,scale,reciprocal),2,SW_RHNE|SW_CLIP_FP,sparse);
   minifloat256 packed=v_f8_pack_b(sparse,SW_GROUP_0|SW_STRIDE_2,(minifloat256)0);
   packed=v_f8_pack_b(sparse,SW_GROUP_1|SW_STRIDE_2,packed);
   packed=v_f8_mov_dual_group_pack_b(packed,SW_PACK21,(minifloat256)0);
   v_f8_st_tnsr_partial(p,output,packed,127,0);
  }
 }
}
